version: '1.0'

services:
  proxy:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - valkey

  valkey:
    image: valkey/valkey
    ports:
      - "6379:6379"